### ISSUE TITLE
Create as-is sitemap

### ISSUE THREAD

**Issue by amanbis** [cdli-gh/mtaac_work#11]
## Summary

Chart out sitemap for existing websites

#### 📈 Progress (0-1): 1

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by epageperron** [comment]
Hello @amanbis This is the sitemap Heather and I looked at right? Do we need to discuss it further so you can close the issue?

**Comment by epageperron** [comment]
@amanbis
