### ISSUE TITLE
Conduct card sort

### ISSUE THREAD

**Issue by amanbis** [cdli-gh/mtaac_work#16]
## Summary

Work with users to categorize content, ideas, problems, and tasks to better identify potential issues and improvements

#### 📈 Progress (0-1): 1

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by amanbis** [comment]
Conducted online and manual cart sort with those familiar with CDLI. Need to conduct card sort with those unfamiliar and then compile data

**Comment by epageperron** [comment]
Please consider the need for a search field which will query both accession number and museum number.
