### ISSUE TITLE
Prepare a CDLI-CoNLL format checker

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#38]
## Summary

We need both structure check and data ( SEGM column markers must match XPOSTAG tags !)

## Other links or relevant information

Before feeding a text to the pre-annotation tool to store entries in the dictionary, also before storing CDLI-CoNLL version of text in the database, the text(s) should be validated following certain rules:   

- [x] No field empty (An underscore should be added in fields where we can’t add something)
- [ ] SEGM and XPOSTAG fields should have corresponding morphemes and tags (I can provide a list)
- [x] Text number and column guide should be conform
- [x] ID column data should be conform

#### 📈 Progress (0-1): 0.8

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by jayanthkmr** [comment]
Have --check_format to check the format, if the format is correct.
Should check format irrespective of the usage of the flag.

**Comment by jayanthkmr** [comment]
@epageperron Some questions I have while implementing it:

* No field empty (An underscore should be added in fields where we can’t add something)
Does this imply we have underscore- "_" for all the fields (ID	FORM	SEGM	XPOSTAG	HEAD	DEPREL	MISC) or just the four fields (ID	FORM	SEGM XPOSTAG), which are part of morphology pre-annotation?

* SEGM and XPOSTAG fields should have corresponding morphemes and tags (I can provide a list) list?
Can you provide the list?

* Text number and column guide should be conform 
What do you mean from this formally? What should I check here?

* ID column data should be conform 
Should I need to check whether ID column data is unique or not? Or do I need to check something more here?

**Comment by epageperron** [comment]
1) Yes, the Conll-U format is strict about that so we should probably be too. But we woudn't want to have to add the underscores manually.
2) https://docs.google.com/spreadsheets/d/1y0_y9HDQNwH0VqDCjjYuUpFsugw4GEybu6Pu01I_D9c/edit#gid=0   Look at the first two columns. There is a little bit of work to do here as some morphemes are "homomorph" or how ever one would call two morphemes that are written the same way but mean different things, the contrary is also true, the same tag can be used to map different morphemes. ( If it's not evident we can go thought it on video, we can also look at annotated texts. It should also be checked that morphemes and tags in their respective columns are present in the lists of tags and morphemes. We should also keep in mind that this should extent to checking out the dictionary for the lemmata at a later stage.
The morphemes and tags lists and mapping should probably be stored in a config file so it is easy to go about and change it if required.

3) Making sure the 2 first lines of the file are present, the first with the text number and the second one with the column headers

4)  Basically just check if the user didn't mess with the ID as they shouldn't be providing or changing them, since ATF2Conll that creates them. 
a) verify that the ID column follows the ID creation rules
b) Please also add a clear comment in ATF2Conll on where and how one can add and modify rules for the creation of the IDs for later

**Comment by jayanthkmr** [comment]
2. Clarification:
The tags are concatened with .
The morphemes and stem are concatened with -
stem is accompanied with meanings in lemma []

https://docs.google.com/spreadsheets/d/1y0_y9HDQNwH0VqDCjjYuUpFsugw4GEybu6Pu01I_D9c/edit#gid=0
https://docs.google.com/spreadsheets/d/1Is7MGG0h8h0vfHj9C9mnWOD2utPeuvm1ZeYb1dsaejg/edit#gid=0

**Comment by epageperron** [comment]
Was this completed? In the case of complex structure we can revisit when we face the problem so we can develop a tailored solution.

**Comment by jayanthkmr** [comment]
The second subtask is still remaining.

**Comment by jayanthkmr** [comment]
@epageperron I will work on this now this week. We can have a meeting tomorrow regarding this.

**Comment by epageperron** [comment]
The CDLI-CoNLL2CoNLL-U converter does some similar check, but I don't remember the details. Maybe look in the code base for the rules? I'm available tomorrow.

**Comment by epageperron** [comment]
@jayanth what's the status on this issue?

**Comment by jayanthkmr** [comment]
@epageperron I believe this can be closed.
