### ISSUE TITLE
Update the about page of the project

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#45]
## Summary

https://github.com/cdli-gh/mtaac/edit/gh-pages/_pages/about.md

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by anandwana001** [comment]
Could you brief about this? What needs to update about?

**Comment by epageperron** [comment]
Updating the list of contributors

**Comment by himanshu007-creator** [comment]
i would like to work on this issue, if it is not yet resolved

**Comment by epageperron** [comment]
It was probably updated since then, it's ben 3 years. Please head to https://gitlab.com/cdli/framework/-/issues for active issues :)
