### ISSUE TITLE
Container and service for the annotation pipeline

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#46]
## Summary

@khoidt will be preparing a bash script to facilitate the work of annotators in the manipulation of the files and tools but we also need to integrate the tools as a service as part of the CDLI infrastructure for further work, after Framework and MTAAC. Editors shouldn't have to install tools, download files, process them and re-upload, although of course the tools should remain available here on Github and usable completely disconnected from CDLI by anyone who would want to.

We have a Python container planned which uses the /tools/ "app" folder in the Framework Gitlab repo 

https://gitlab.com/cdli/framework/tree/phoenix/develop/app/tools/

But because of the click (http://click.pocoo.org/5/) maybe we can install the tools while deploying the container itself, I'm not sure what is best practice here (@nomoon ?).

Cake/Shell should be able to communicate with the Python container and run the tools and process files. 

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by jayanthkmr** [comment]
@epageperron  Do you mean [this](https://spin.atomicobject.com/2015/11/30/command-line-tools-docker/) ?


The biggest downside of this approach is that it requires users to first have Docker installed. Depending on your application, however, having a single dependency on Docker may be much simpler to support.

**Comment by epageperron** [comment]
I'll edit the issue to add details and make it more clear

**Comment by epageperron** [comment]
Done.

**Comment by epageperron** [comment]
This issue was moved to cdli-gh/Framework#82
