### ISSUE TITLE
ATF Checker

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#5]
As part of the pre-processing phase, we need to validate the structure of the ATF and it's content. To do this, we are updating our checkers from the ORACC ATF checker and the CDLI words and sign checker into an integrated and complete solution. 
<hr>
Initial tasks instructions:

1.  ATF SCRUBBER  *add scrubber of all ATF content to MySQL to ensure it is compliant UTF-8 and unix lf; should also check that numbered ATF lines are strictly simple ASCII*   
1.  ATF CHECKER  *implement atf checker supplied by Tinney*   
1. ATF TOKENS CHECKER  *combine with atf checker page now used in cdli*   

<hr>
See this documents for rules to integrate and problems encountered while going through the lists of generated tokens:

https://docs.google.com/document/d/1nQATxrLgrZSt8Plw96LDTVwgcXZFIzRpZCH51sTbZBk/edit 

**Preprocessing**
- [x] Collect errors from pyoracc
- [x] Collect errors from ORACC atf checker
...

**Structure validator**
- [x] Ensure file is UTF-8 and that translit lines are ASCII
...

**Integration with PyORACC**
- [x] Integrate all the current checks with pyoracc
...

**Tokens validator**
- [ ] Prepare the tokenizer so it outputs proper lists of words and signs without any erroneous entries and proper frequency
...
**Interface**
...
**Others**
- [ ] Write the documentation on the functioning of the checker
- [ ] Write the documentation on the usage of the checker
- [ ] Justify the technology used (why wasn't pyoracc modified and reused, why was the tokenizer rewritten) in the docs

#### 📈 Progress (0-1): 0.1

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by epageperron** [comment]
The description needs to be updated based on recent discussion and further consultation among participants in the task.

**Comment by jayanthkmr** [comment]
@epageperron can we close this issue or update the description? It is better to close it, imho.

**Comment by epageperron** [comment]
Please open a new one ( a minimal one ) so we can track it on waffle and the Gantt chart.
