### ISSUE TITLE
Integrate bootstrap into codebase

### ISSUE THREAD

**Issue by amanbis** [cdli-gh/mtaac_work#55]
## Summary

Integrate Bootstrap into codebase for front-end

## Other links or relevant information

https://getbootstrap.com/

#### 📈 Progress (0-1): 1

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by epageperron** [comment]
I thought that was solved with merging @amaaniqbal 's change in file paths?

**Comment by amaaniqbal** [comment]
Yes, I have done that on GitLab.

@amanbis can you please tell what did you mean by this?

**Comment by amanbis** [comment]
Bootstrap was added by CDN
