### ISSUE TITLE
Implement SASS

### ISSUE THREAD

**Issue by amanbis** [cdli-gh/mtaac_work#56]
## Summary

Implement SASS into fronte-end workflow

## Other links or relevant information

https://sass-lang.com/

#### 📈 Progress (0-1): 0

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

**Comment by epageperron** [comment]
@amaaniqbal can you please look into this if you have time?

**Comment by amaaniqbal** [comment]
Sure, I will be looking into it! 
Before that @amanbis, have you tried the way or tool which I suggested on Slack?

PS: Gantt is not loading.

**Comment by epageperron** [comment]
Yes our gantt charts are dead and I won't set them back up until after I have reevaluated the work plan in full.. I'll announce it when it's back up :-)

**Comment by amaaniqbal** [comment]
Ohh okay! 
I will start working on this issue, as soon as Aman confirms, if my suggested way to work with this doesn't work or if there was some issue.

**Comment by epageperron** [comment]
Setup done by @amanbis
