### ISSUE TITLE
Normalization of ATF

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/mtaac_work#6]
After the ATF has been checked for structure, for conformity to token lists and harmonized to the best of our abilities, we need to prepare a normalization script that will remove unneeded data for NLP. Such data are for instance line numbering, comments, heather metadata, etc. 

- [x] Take an archival snapshot of the ATF before starting the annotations
- [x] Prepare a script that will normalize the data (Check before if one of our clean database fields does the job)
- [ ] Verify the quality of the normalization with Assyriologists and correct the script as needed
- [ ] Produce a normalized copy of the ATF

**Comment by epageperron** [comment]
@khoidt it would be helpful if you could describe exactly what normalized textual data should look like

**Comment by khoidt** [comment]
Now in https://github.com/cdli-gh/mtaac_work/tree/master/ATF_transliteration_processor.

**Comment by epageperron** [comment]
Is this task done? I understand it might need to be modified slightly for different lemmatizers but the script works and does what it is intended for yes? Can we close the issue ?

**Comment by khoidt** [comment]
Yes, this is done
